#!/bin/sh
set -eu
HOSTKEY_DIR=/etc/ssh/hostkey.d

generate_hostkeys() {
    find "$HOSTKEY_DIR" -maxdepth 1 -type f -name 'ssh_host_*' -exec cp '{}' /etc/ssh \;
    ssh-keygen -A
    find "/etc/ssh" -maxdepth 1 -type f -name 'ssh_host_*' -exec cp '{}' "$HOSTKEY_DIR" \;
}

generate_hostkeys
/usr/local/bin/create-users
/usr/sbin/sshd -D -e
